# Generated by Django 3.2.16 on 2022-11-01 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_recipe_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'Supplies'},
        ),
        migrations.AddField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 6, 33, 10, 496912, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='production',
            unique_together={('product', 'date')},
        ),
        migrations.CreateModel(
            name='ProductionIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplyitem')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.production')),
            ],
        ),
    ]
