# Generated by Django 3.2.16 on 2022-11-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20221101_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity_produced',
            field=models.FloatField(default=500, help_text='How many this recipe will produce for the product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity of the ingredient used')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.supplyitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.recipe')),
            ],
        ),
    ]
