# Generated by Django 3.2.16 on 2022-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20221101_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='multiplied_by_production',
            field=models.BooleanField(default=False),
        ),
    ]
