# Generated by Django 3.2.16 on 2022-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_ingredient_multiplied_by_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='actual_sale',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='freebies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='projected_sale',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
