# Generated by Django 3.2.16 on 2022-11-01 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20221101_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 18, 2, 48, 703105, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
