# Generated by Django 3.2.16 on 2022-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20221102_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='actual_sale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='freebies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
