# Generated by Django 3.2.16 on 2022-11-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20221102_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioningredients',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='backend.production'),
        ),
    ]
