# Generated by Django 3.2.25 on 2024-08-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20230112_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='actual_sale',
            field=models.FloatField(blank=True, help_text='Actual sale input by user', null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='projected_sale',
            field=models.FloatField(help_text='Projected sale is the sale calculated by the system'),
        )
    ]
