version: '3'

services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: ./Dockerfile.dev
    volumes:
      - web-static:/usr/src/app/static
      - ./web:/usr/src/app
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env


volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
