version: '3'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - web-static:/usr/src/app/static
      - ./backend:/usr/src/app
    env_file: .env
    command: /usr/src/app/local-entrypoint.sh
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DEBUG: 'True'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000/api
      CHOKIDAR_USEPOLLING: 'true'
    command: npm run dev
    depends_on:
      backend:
        condition: service_started
    
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
