version: '3'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - web-static:/usr/src/app/static
      - ./backend:/usr/src/app
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DEBUG: 'True'
  
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://backend:8000/api
      NEXT_PUBLIC_API_URL: http://backend:8000/api
      CHOKIDAR_USEPOLLING: 'true'
    
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env


volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
