version: '3'

services:
  web:
    restart: always
    build: ./web
    volumes:
      - web-static:/usr/src/app/static
      - ./web:/usr/src/app
    env_file: .env
    depends_on:
      - db
    

  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - web-static:/static
      - ./web:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - web
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
