version: '3'

services:
  web:
    restart: always
    build: ./web
    volumes:
      - web-static:/usr/src/app/static
      - ./web:/usr/src/app
    env_file: .env

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
