version: '3'

services:
  web:
    restart: always
    build: ./web
    volumes:
      - web-static:/usr/src/app/static
      - ./web:/usr/src/app
    env_file: .env
    depends_on:
      - db
    

  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - web-static:/static
      - ./web:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - web

  db:
    restart: always
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
