version: '3'

services:
  backend:
    restart: always
    volumes:
      - web-static:/usr/src/app/static
      - backend:/usr/src/app
    env_file: .env
  
  frontend:
    restart: always
    volumes:
      - frontend:/usr/src/app


volumes:
  web-django:
  web-static:
